{%set name = "Fabric3" %}
{%set version = "1.14.post1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "647e485ec83f30b587862f92374d6affc217f3d79819d1d7f512e42e7ae51e81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
build:
  entry_points:
    - fab = fabric.main:main
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - paramiko >=1.17.2,<2.0
    - six >=1.10.0

test:
  imports:
    - fabric
    - fabric.contrib

  commands:
    - fab --help

about:
  home: https://github.com/mathiasertl/fabric/
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Fabric is a simple, Pythonic tool for remote execution and deployment (py2.7/py3.4+ compatible fork).'
  license_family: BSD
  dev_url: https://github.com/mathiasertl/fabric/

extra:
  recipe-maintainers:
    - pmlandwehr
