travis:
  secure:
    BINSTAR_TOKEN: kZqSUcVdM7eJxEzBYoHVkC9r7Tk2thkxZ1wcOmV6nSVEuXnYO723wAYav+SkjzHImvGswkMFCyRRaLkBhvKML8n1NN3gGC8HikuTu3YlFwLn65mHGvnchG2oqeoHxlxEtAeilNDwoHB1s/nanaxeq91Qy9Fq0iebVO1xEFt2KMsPittzjLuVyaSVDeV+iJrJcCinNl3MB2+A3jtx6RlHMa8IUm29rjlakU4R4bVReivvG3WieWo8GN7YuRGiYEuYdSTIQVvijFyWbjMxmSC1ZrvtSF286KefJ8PxoC0oWT28xH2kbMoCftnR+Geq7fPGpu6pOAyTE+cLD0rkGzHCsZDS8GXoRUv6cdxL9m2n9LvLYuktzcCxYxPuO9F/s76ooMME2C2bs/VyLkTsPnNdQuD1avcld8d27jeTb8fHssUzlygyH/ccM0e0unO/LAoWA5Q4JebfY4eGKnHxsGyt35t+l77/shKzPhEDmMSXBEqfpIgVNL4eGI2RABjXWFlyF+oCrlx16k8mGEH9mhpdy4CQxSKtsqVqd6NL8tbDbod76/RXr4Zb6uPNOTU0Q68FAv01cEoKbq6pvTurhNNJ4uSuxHevwV2nPpInM7VJoPe+JaEPXhGHarRGbbVZF9IoJQIW78JAn4e3E4U+YI4GwFUR9cOKHd+hUGXAbPW4ZZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
